import React, { createContext, useContext } from "react";
import { TextureLoader } from "three";
import { useLoader } from "@react-three/fiber";
//import { tileTextures } from "@/utils/textures";

const AssetsContext = createContext({});

type AssetLoaderProps = {
  children: React.ReactNode;
};

const texturePaths = {
  grass1: "static/textures/tiles/grass/grass_06.png",
  grass2: "static/textures/tiles/grass/grass_08.png",
  grass3: "static/textures/tiles/grass/grass_14.png",
  grass4: "static/textures/tiles/grass/grass_15.png",
  plot: "static/textures/tiles/sand/sand_07.png",
  topLeftCorner: "static/textures/tiles/sand/sand_00.png",
  topRightCorner: "static/textures/tiles/sand/sand_02.png",
  bottomRightCorner: "static/textures/tiles/sand/sand_14.png",
  bottomLeftCorner: "static/textures/tiles/sand/sand_12.png",
  leftEdge: "static/textures/tiles/sand/sand_06.png",
  rightEdge: "static/textures/tiles/sand/sand_08.png",
  topEdge: "static/textures/tiles/sand/sand_01.png",
  bottomEdge: "static/textures/tiles/sand/sand_13.png",
  rock: "static/textures/rock.png",
  bell0: "static/textures/plants/bell/bell_00.png",
  bell1: "static/textures/plants/bell/bell_01.png",
  bell2: "static/textures/plants/bell/bell_02.png",
  bell3: "static/textures/plants/bell/bell_03.png",
  bell4: "static/textures/plants/bell/bell_04.png",
  bell5: "static/textures/plants/bell/bell_05.png",
  bell6: "static/textures/plants/bell/bell_06.png",
  bell7: "static/textures/plants/bell/bell_07.png",
  bell8: "static/textures/plants/bell/bell_08.png",
  bell9: "static/textures/plants/bell/bell_09.png",
  bell10: "static/textures/plants/bell/bell_10.png",
  bell11: "static/textures/plants/bell/bell_11.png",
  bell12: "static/textures/plants/bell/bell_12.png",
  bell13: "static/textures/plants/bell/bell_13.png",
  bell14: "static/textures/plants/bell/bell_14.png",
  bell15: "static/textures/plants/bell/bell_15.png",
  bell16: "static/textures/plants/bell/bell_16.png",
  bell17: "static/textures/plants/bell/bell_17.png",
  bell18: "static/textures/plants/bell/bell_18.png",
  bell19: "static/textures/plants/bell/bell_19.png",
  bell20: "static/textures/plants/bell/bell_20.png",
  bell21: "static/textures/plants/bell/bell_21.png",
  bell22: "static/textures/plants/bell/bell_22.png",
  bell23: "static/textures/plants/bell/bell_23.png",
  bell24: "static/textures/plants/bell/bell_24.png",
  sprout0: "static/textures/plants/sprout/sprout_00.png",
  sprout1: "static/textures/plants/sprout/sprout_01.png",
  sprout2: "static/textures/plants/sprout/sprout_02.png",
  sprout3: "static/textures/plants/sprout/sprout_03.png",
  sprout4: "static/textures/plants/sprout/sprout_04.png",
  sprout5: "static/textures/plants/sprout/sprout_05.png",
  sprout6: "static/textures/plants/sprout/sprout_06.png",
  sprout7: "static/textures/plants/sprout/sprout_07.png",
  sprout8: "static/textures/plants/sprout/sprout_08.png",
  sprout9: "static/textures/plants/sprout/sprout_09.png",
  sprout10: "static/textures/plants/sprout/sprout_10.png",
  sprout11: "static/textures/plants/sprout/sprout_11.png",
  sprout12: "static/textures/plants/sprout/sprout_12.png",
  sprout13: "static/textures/plants/sprout/sprout_13.png",
  sprout14: "static/textures/plants/sprout/sprout_14.png",
  sprout15: "static/textures/plants/sprout/sprout_15.png",
  sprout16: "static/textures/plants/sprout/sprout_16.png",
  sprout17: "static/textures/plants/sprout/sprout_17.png",
  sprout18: "static/textures/plants/sprout/sprout_18.png",
  sprout19: "static/textures/plants/sprout/sprout_19.png",
  sprout20: "static/textures/plants/sprout/sprout_20.png",
  sprout21: "static/textures/plants/sprout/sprout_21.png",
  sprout22: "static/textures/plants/sprout/sprout_22.png",
  sprout23: "static/textures/plants/sprout/sprout_23.png",
  sprout24: "static/textures/plants/sprout/sprout_24.png",
  salvia0: "static/textures/plants/salvia/salvia_00.png",
  salvia1: "static/textures/plants/salvia/salvia_01.png",
  salvia2: "static/textures/plants/salvia/salvia_02.png",
  salvia3: "static/textures/plants/salvia/salvia_03.png",
  salvia4: "static/textures/plants/salvia/salvia_04.png",
  salvia5: "static/textures/plants/salvia/salvia_05.png",
  salvia6: "static/textures/plants/salvia/salvia_06.png",
  salvia7: "static/textures/plants/salvia/salvia_07.png",
  salvia8: "static/textures/plants/salvia/salvia_08.png",
  salvia9: "static/textures/plants/salvia/salvia_09.png",
  salvia10: "static/textures/plants/salvia/salvia_10.png",
  salvia11: "static/textures/plants/salvia/salvia_11.png",
  salvia12: "static/textures/plants/salvia/salvia_12.png",
  salvia13: "static/textures/plants/salvia/salvia_13.png",
  salvia14: "static/textures/plants/salvia/salvia_14.png",
  salvia15: "static/textures/plants/salvia/salvia_15.png",
  salvia16: "static/textures/plants/salvia/salvia_16.png",
  salvia17: "static/textures/plants/salvia/salvia_17.png",
  salvia18: "static/textures/plants/salvia/salvia_18.png",
  salvia19: "static/textures/plants/salvia/salvia_19.png",
  salvia20: "static/textures/plants/salvia/salvia_20.png",
  salvia21: "static/textures/plants/salvia/salvia_21.png",
  salvia22: "static/textures/plants/salvia/salvia_22.png",
  salvia23: "static/textures/plants/salvia/salvia_23.png",
  salvia24: "static/textures/plants/salvia/salvia_24.png",
};

export type AssetsType = typeof texturePaths;

export const AssetLoader = ({ children }: AssetLoaderProps) => {
  // TODO - load textures from the server
  const textures = useLoader(TextureLoader, [...Object.values(texturePaths)]);

  const assets = {
    grass1: textures[0],
    grass2: textures[1],
    grass3: textures[2],
    grass4: textures[3],
    plot: textures[4],
    topLeftCorner: textures[5],
    topRightCorner: textures[6],
    bottomRightCorner: textures[7],
    bottomLeftCorner: textures[8],
    leftEdge: textures[9],
    rightEdge: textures[10],
    topEdge: textures[11],
    bottomEdge: textures[12],
    rock: textures[13],
    bell0: textures[14],
    bell1: textures[15],
    bell2: textures[16],
    bell3: textures[17],
    bell4: textures[18],
    bell5: textures[19],
    bell6: textures[20],
    bell7: textures[21],
    bell8: textures[22],
    bell9: textures[23],
    bell10: textures[24],
    bell11: textures[25],
    bell12: textures[26],
    bell13: textures[27],
    bell14: textures[28],
    bell15: textures[29],
    bell16: textures[30],
    bell17: textures[31],
    bell18: textures[32],
    bell19: textures[33],
    bell20: textures[34],
    bell21: textures[35],
    bell22: textures[36],
    bell23: textures[37],
    bell24: textures[38],
    bell25: textures[39],
    sprout0: textures[40],
    sprout1: textures[41],
    sprout2: textures[42],
    sprout3: textures[43],
    sprout4: textures[44],
    sprout5: textures[45],
    sprout6: textures[46],
    sprout7: textures[47],
    sprout8: textures[48],
    sprout9: textures[49],
    sprout10: textures[50],
    sprout11: textures[51],
    sprout12: textures[52],
    sprout13: textures[53],
    sprout14: textures[54],
    sprout15: textures[55],
    sprout16: textures[56],
    sprout17: textures[57],
    sprout18: textures[58],
    sprout19: textures[59],
    sprout20: textures[60],
    sprout21: textures[61],
    sprout22: textures[62],
    sprout23: textures[63],
    sprout24: textures[64],
    salvia0: textures[65],
    salvia1: textures[66],
    salvia2: textures[67],
    salvia3: textures[68],
    salvia4: textures[69],
    salvia5: textures[70],
    salvia6: textures[71],
    salvia7: textures[72],
    salvia8: textures[73],
    salvia9: textures[74],
    salvia10: textures[75],
    salvia11: textures[76],
    salvia12: textures[77],
    salvia13: textures[78],
    salvia14: textures[79],
    salvia15: textures[80],
    salvia16: textures[81],
    salvia17: textures[82],
    salvia18: textures[83],
    salvia19: textures[84],
    salvia20: textures[85],
    salvia21: textures[86],
    salvia22: textures[87],
    salvia23: textures[88],
    salvia24: textures[89],
  } as const;

  return (
    <AssetsContext.Provider value={{ ...assets }}>
      {children}
    </AssetsContext.Provider>
  );
};

export const useAssets = () => useContext(AssetsContext);
