export const tileTextures = {
  grass: {
    0: "/TileSet/Grass/Grass_00.png",
    1: "/TileSet/Grass/Grass_01.png",
    2: "/TileSet/Grass/Grass_02.png",
    3: "/TileSet/Grass/Grass_03.png",
    4: "/TileSet/Grass/Grass_04.png",
    5: "/TileSet/Grass/Grass_05.png",
    6: "/TileSet/Grass/Grass_06.png",
    7: "/TileSet/Grass/Grass_07.png",
    8: "/TileSet/Grass/Grass_08.png",
    9: "/TileSet/Grass/Grass_09.png",
    10: "/TileSet/Grass/Grass_10.png",
    11: "/TileSet/Grass/Grass_11.png",
    12: "/TileSet/Grass/Grass_12.png",
    13: "/TileSet/Grass/Grass_13.png",
    14: "/TileSet/Grass/Grass_14.png",
    15: "/TileSet/Grass/Grass_15.png",
    16: "/TileSet/Grass/Grass_16.png",
    17: "/TileSet/Grass/Grass_17.png",
    18: "/TileSet/Grass/Grass_18.png",
    19: "/TileSet/Grass/Grass_19.png",
    20: "/TileSet/Grass/Grass_20.png",
  } as { [key: number]: string },
  sand: {
    topLeftCorner: "/TileSet/Sand/Sand_00.png",
    topRow: "/TileSet/Sand/Sand_01.png",
    topRightCorner: "/TileSet/Sand/Sand_02.png",
    leftColumn: "/TileSet/Sand/Sand_06.png",
    rightColumn: "/TileSet/Sand/Sand_08.png",
    center1: "/TileSet/Sand/Sand_07.png",
    center2: "/TileSet/Sand/Sand_15.png",
    center3: "/TileSet/Sand/Sand_16.png",
    bottomRow: "/TileSet/Sand/Sand_13.png",
    bottomLeftCorner: "/TileSet/Sand/Sand_12.png",
    bottomRightCorner: "/TileSet/Sand/Sand_14.png",
  },
};

export const plantTextures = {
  salvia: {
    0: "/plants/salvia/salvia_00.png",
    1: "/plants/salvia/salvia_01.png",
    2: "/plants/salvia/salvia_02.png",
    3: "/plants/salvia/salvia_03.png",
    4: "/plants/salvia/salvia_04.png",
    5: "/plants/salvia/salvia_05.png",
    6: "/plants/salvia/salvia_06.png",
    7: "/plants/salvia/salvia_07.png",
    8: "/plants/salvia/salvia_08.png",
    9: "/plants/salvia/salvia_09.png",
    10: "/plants/salvia/salvia_10.png",
    11: "/plants/salvia/salvia_11.png",
    12: "/plants/salvia/salvia_12.png",
    13: "/plants/salvia/salvia_13.png",
    14: "/plants/salvia/salvia_14.png",
    15: "/plants/salvia/salvia_15.png",
    16: "/plants/salvia/salvia_16.png",
    17: "/plants/salvia/salvia_17.png",
    18: "/plants/salvia/salvia_18.png",
    19: "/plants/salvia/salvia_19.png",
    20: "/plants/salvia/salvia_20.png",
    21: "/plants/salvia/salvia_21.png",
    22: "/plants/salvia/salvia_22.png",
    23: "/plants/salvia/salvia_23.png",
    24: "/plants/salvia/salvia_24.png",
  } as { [key: number]: string },
};
