import { Tile } from "@/gameComponents/Tile";

export const WorldScene = () => {
  // G is grass, P is a garden plot
  const tileMap = `
    GGGGGGGGGGGGGGGGGGGGGGGGGGGG
    GGGGGGGGGGGGGGGGGGGGGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGPPPPPPPPPPPPPPPGGGGGGGG
    GGGGGGGGGGGGGGGGGGGGGGGGGGGG
    GGGGGGGGGGGGGGGGGGGGGGGGGGGG
    GGGGGGGGGGGGGGGGGGGGGGGGGGGG
    GGGGGGGGGGGGGGGGGGGGGGGGGGGG`;
  const renderTileMap = () => {
    const rows = tileMap.trim().split("\n").reverse();
    const mapWidth = rows[0].length;
    const mapHeight = rows.length;
    const xOffset = -mapWidth / 2;
    const yOffset = -mapHeight / 2;

    return rows.map((row, y) => {
      return row.split("").map((type, x) => {
        return <Tile type={type} position={[x + xOffset, y + yOffset]} />;
      });
    });
  };

  return <>{renderTileMap()}</>;
};
